### ISSUE TITLE
Could not find prot_lig_prod_all.dcd

### ISSUE THREAD

**Issue by pharm-dacnhan** [quantaosun/Ambertools-OpenMM-MD#3]
In the final step, I faced with the following error, can you help me figure out my problem? 

Error: Error(s) occurred during execution.
  File "/usr/local/bin/MMPBSA.py", line 99, in <module>
    app.file_setup()
  File "/usr/local/lib/python3.10/site-packages/MMPBSA_mods/main.py", line 161, in file_setup
    self.numframes, self.numframes_nmode = make_trajectories(INPUT, FILES,
  File "/usr/local/lib/python3.10/site-packages/MMPBSA_mods/make_trajs.py", line 59, in make_trajectories
    traj = Trajectory(FILES.solvated_prmtop, FILES.mdcrd, cpptraj)
  File "/usr/local/lib/python3.10/site-packages/MMPBSA_mods/make_trajs.py", line 506, in __init__
    self.Query()
  File "/usr/local/lib/python3.10/site-packages/MMPBSA_mods/make_trajs.py", line 641, in Query
    raise TrajError('%s failed when querying %s' % (self.exe, traj))
TrajError: /usr/local/bin/cpptraj failed when querying prot_lig_prod_all.dcd

**Comment by pharm-dacnhan** [comment]
> This is my mmpbsa.in content

f = open("mmpbsa.in", "w")
f.write("""&general """  + "\n"
"""  endframe=""" + str(int(1000)) + """,  interval=""" + str(int(100)) + """, strip_mask=:WAT:Na+:Cl-:Mg+:K+, """ + "\n"
"""/ """ + "\n"
#MMGBSA calculation
"""&gb """ + "\n"
""" igb=""" + str(5) +  """, saltcon=""" + str(0.150) +  """, """ + "\n"
"""/ """ + "\n"
#MMPBSA CALCULATION
"""&pb """ + "\n"
""" istrng=""" + str(0.150) +  """, inp=2, radiopt=0, prbrad=1.4, """ + "\n"
"""/""")
f.close()

**Comment by quantaosun** [comment]
Hi,

I probably have written it in more detail, the mmpbsa code in my notebook is never expected to be used directly since I assume most of my readers already have been familiar with Amber. That is in the parameterisation steps, better to generate all prmtop files for receptor, ligand, etc, or later you could also extract from complex.prmtop. That is something I have not but probably should included in the notebook.

 In my notebook, the final trajectory name is trajectory.dcd.  Also, you are supposed to change the number of frames used in mmpbsa based actual number of frames in your trajectory file. These are all very basic things people would look at. 

I should assure you that a simple MMPBSA or MMGBSA is not hard at all if you don't try to do energy decomposition or other things like Alaine scanning etc. So please just read Amber's manual probably is more efficient than posting here. I will update the notebook eventually but this is not a priority for now. Cheers.

In a general sense about these issues you have raised recently, I would suggest

1- use [pablo-arantes](https://github.com/pablo-arantes/making-it-rain/commits?author=pablo-arantes) if your goal is just to finish some job, it is probably the easiest way to do it.

2- Use gmx_MMPBSA https://valdes-tresanco-ms.github.io/gmx_MMPBSA/dev/ , if you just want to finish a job and want nice figures and images of mmpbsa analysis.

But if your goal is to develop some script for your project, and you have to use Amber, then probably you have to read Amber's MMPBSA manual quite carefully.
